var AuthConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_CHECK: "LOGIN_CHECK",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  UPDATE_SESSION: "UPDATE_SESSION",
  RECEIVE_USER_INFO: "RECEIVE_USER_INFO"
};

module.exports = AuthConstants;
