---
development:
  cloud_name: thadowg
  api_key: '863347724593944'
  api_secret: VM97F6cf_zg3gzQ-lMJtkYOaes8
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: thadowg
  api_key: '863347724593944'
  api_secret: VM97F6cf_zg3gzQ-lMJtkYOaes8
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: thadowg
  api_key: '863347724593944'
  api_secret: VM97F6cf_zg3gzQ-lMJtkYOaes8
  enhance_image_tag: true
  static_image_support: false
